name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        modules: 'qtdeclarative qtquickcontrols2'
        dir: '${{ github.workspace }}/qt'
        cache: true

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Clean and Create Build Directory
      working-directory: test
      run: |
        rm -rf build CMakeCache.txt CMakeFiles
        mkdir -p build

    - name: Configure CMake
      working-directory: test/build
      run: |
        cmake -DCMAKE_PREFIX_PATH=${{ github.workspace }}/qt/6.5.3/gcc_64 -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      working-directory: test/build
      run: cmake --build .
