name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt6-base-dev qt6-declarative-dev qml6-module-qtquick qml6-module-qtquick-controls

    - name: Create Build Directory
      working-directory: test
      run: mkdir -p build

    - name: Configure CMake
      working-directory: test/build
      run: cmake ..

    - name: Build
      working-directory: test/build
      run: cmake --build . --config Release
